services:
  busco:
    container_name: busco
    image: ezlabgva/busco:v6.0.0_cv1
    volumes: 
      - ./data/genomes_raw:/input:ro
      - ./data/busco:/output
      - ./scripts/run_busco.sh:/docker-entrypoint.sh
    platform: linux/amd64 
    entrypoint: "/docker-entrypoint.sh"

  quast:
    build:
      context: .
      dockerfile: docker/quast/Dockerfile
    image: quast:5.2.0
    container_name: quast
    volumes:
      - ./data/genomes_raw:/input:ro
      - ./data/quast:/output
      - ./scripts/run_quast.sh:/docker-entrypoint.sh
    entrypoint: "/docker-entrypoint.sh"
